### ISSUE TITLE
关于博客“more”标签的问题？

### ISSUE THREAD

**Issue by dondurma** [fan-haobai/blog#9]
楼主你好！很高心用了和你一样的主题，自己不是从事的前端开发，所以很好奇你的博客这个地方是怎么去掉的？迫切希望能够得到楼主的解答！！！
[http://m.qpic.cn/psb?/V14IquGe120hrs/cF22V6PinmYRElixC22CO57u2Dp8fN497dxGCHaXIjQ!/b/dDQBAAAAAAAA&bo=qQIvAQAAAAADB6c!&rf=viewer_4](http://m.qpic.cn/psb?/V14IquGe120hrs/cF22V6PinmYRElixC22CO57u2Dp8fN497dxGCHaXIjQ!/b/dDQBAAAAAAAA&bo=qQIvAQAAAAADB6c!&rf=viewer_4)

**Comment by fan-haobai** [comment]
> 楼主你好！很高心用了和你一样的主题，自己不是从事的前端开发，所以很好奇你的博客这个地方是怎么去掉的？迫切希望能够得到楼主的解答！！！
> http://m.qpic.cn/psb?/V14IquGe120hrs/cF22V6PinmYRElixC22CO57u2Dp8fN497dxGCHaXIjQ!/b/dDQBAAAAAAAA&bo=qQIvAQAAAAADB6c!&rf=viewer_4

就一个配置就好了，见 https://github.com/fan-haobai/hexo-theme-yilia/blob/master/_config.yml 的 show_all_link 配置。

**Comment by fan-haobai** [comment]
@dondurma 见这个部分 https://github.com/fan-haobai/hexo-theme-yilia/blob/master/_config.yml
